development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"

test:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"

  production:
  secret_key_base: <%= secure_token %>
  LINKEDIN_KEY: '86216f721b4p1x'
  LINKEDIN_SECRET: 'wusom7Y1g0MVfdvu'